//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Run_Conquer_Server.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameModelContainer : DbContext
    {
        public GameModelContainer()
            : base("name=GameModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Player> PlayerSet { get; set; }
        public DbSet<GameInstance> GameInstanceSet { get; set; }
        public DbSet<Team> TeamSet { get; set; }
        public DbSet<Map> MapSet { get; set; }
    }
}
