//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Run_Conquer_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public Map()
        {
            this.LatLon = new PositionType();
            this.Size = new PositionType();
        }
    
        public int Id { get; set; }
        public Nullable<int> Zoom { get; set; }
    
        public PositionType LatLon { get; set; }
        public PositionType Size { get; set; }
    
        public virtual GameInstance GameInstance { get; set; }
    }
}
