//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Run_Conquer_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Position = new PositionType();
        }
    
        public int Id { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        public PositionType Position { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
